site_name: Layman's Path
site_url: http://127.0.0.1:8000/

nav:
  - Home: index.md
  - About: about.md
  - Contact: contact.md

theme:
  name: material
  palette:
    primary: purple
    accent: light green
  logo: assets/DreamcatcherLogo.png
