site_name: Layman's Path
site_url: https://2dreamwatch.github.io/laymanspath/

nav:
  - Home: index.md
  - About: about.md
  - Contact: contact.md

theme:
  name: material
  palette:
    primary: purple
    accent: light green
  logo: assets/DreamcatcherLogo.png
